# https://goframe.org/docs/web/server-config-file-template
server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  level : "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
database:
  default:
    link: "mysql:root:root1234@tcp(127.0.0.1:13306)/db4?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  checkin:
    address: "127.0.0.1:6379"
    password: ""

snowflake:
  startTime: "2025-01-01"