// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package checkin

import (
	"backend/api/checkin"
	srvCheckin "backend/internal/service/checkin"
	"backend/internal/service/checkin/impl"
)

type ControllerV1 struct {
	svc srvCheckin.Service
}

func NewV1() checkin.ICheckinV1 {
	return &ControllerV1{
		svc: impl.NewService(),
	}
}
