// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"backend/api/user"                      // api层的user包
	srvUser "backend/internal/service/user" // service层的user包
	"backend/internal/service/user/impl"
)

type ControllerV1 struct {
	svc srvUser.UserInfoService // 用户信息服务

}

func NewV1() user.IUserV1 {
	return &ControllerV1{
		svc: impl.New(),
	}
}
