// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package points

import (
	"backend/api/points"
	srvPoints "backend/internal/service/points"
	"backend/internal/service/points/impl"
)

type ControllerV1 struct {
	svc srvPoints.Service
}

func NewV1() points.IPointsV1 {
	return &ControllerV1{
		svc: impl.New(),
	}
}
