// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// userinfoDao is the data access object for the table userinfo.
// You can define custom methods on it to extend its functionality as needed.
type userinfoDao struct {
	*internal.UserinfoDao
}

var (
	// Userinfo is a globally accessible object for table userinfo operations.
	Userinfo = userinfoDao{internal.NewUserinfoDao()}
)

// Add your custom methods and functionality below.
