// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// userPointsTransactionsDao is the data access object for the table user_points_transactions.
// You can define custom methods on it to extend its functionality as needed.
type userPointsTransactionsDao struct {
	*internal.UserPointsTransactionsDao
}

var (
	// UserPointsTransactions is a globally accessible object for table user_points_transactions operations.
	UserPointsTransactions = userPointsTransactionsDao{internal.NewUserPointsTransactionsDao()}
)

// Add your custom methods and functionality below.
