// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// userCheckinRecordsDao is the data access object for the table user_checkin_records.
// You can define custom methods on it to extend its functionality as needed.
type userCheckinRecordsDao struct {
	*internal.UserCheckinRecordsDao
}

var (
	// UserCheckinRecords is a globally accessible object for table user_checkin_records operations.
	UserCheckinRecords = userCheckinRecordsDao{internal.NewUserCheckinRecordsDao()}
)

// Add your custom methods and functionality below.
